let dados = [
    {
        titulo: "Uma Advogada Extraordinária",
        descricao: "Uma Advogada Extraordinária narra a história de uma jovem advogada com habilidades incríveis, desafiando todas as expectativas em sua carreira e vida pessoal.",
        link: "https://pt.wikipedia.org/wiki/Uma_Advogada_Extraordin%C3%A1ria",
        tags: "advogada extraordinária série",
        ano: 2022,
        episodios: 16,
        elenco: ["Park Eun-bin", "Kang Tae-oh"],
        plataforma: "Netflix",
        nota: 4.5,
        imagem: "https://i.pinimg.com/originals/78/2b/79/782b797e12916540363b88e205cafbb0.jpg"
    },
    {
        titulo: "Pousando no Amor",
        descricao: "Pousando no Amor conta a história de uma herdeira sul-coreana que, após um acidente de parapente, acaba na Coreia do Norte, onde conhece um oficial do exército norte-coreano. Juntos, eles enfrentam desafios para mantê-la segura e retorná-la ao seu país.",
        link: "https://pt.wikipedia.org/wiki/Pousando_no_Amor",
        tags: "pousando no amor romance dorama coreano",
        ano: 2019,
        episodios: 16,
        elenco: ["Son Ye-jin", "Hyun Bin"],
        plataforma: "Netflix",
        nota: 4.7,
        imagem: "https://i.pinimg.com/564x/55/6e/86/556e861d10fd4b70d81e182b8af6d154.jpg"
    },
    {
        titulo: "Intensivão do Amor",
        descricao: "Intensivão do Amor é uma comédia romântica que explora a busca pelo amor verdadeiro entre um grupo de amigos em um cenário dinâmico e engraçado.",
        link: "https://www.netflix.com/br/title/81649877",
        tags: "romance comédia amor",
        ano: 2023,
        episodios: 16,
        elenco: ["Jeon Do-yeon", "Jung Kyung-ho", "Lee Bong-ryeon"],
        plataforma: "Netflix",
        nota: 4.3,
        imagem: "https://i.pinimg.com/564x/1c/3c/4b/1c3c4b48f1192f425db7d63936bda541.jpg"
    },
    {
        titulo: "Rainha das Lágrimas",
        descricao: "Rainha das Lágrimas é um drama emocionante que acompanha as dificuldades e superações de uma mulher que enfrenta tragédias em sua vida pessoal e profissional.",
        link: "https://pt.wikipedia.org/wiki/Rainha_das_L%C3%A1grimas",
        tags: "drama lágrimas superação",
        ano: 2024,
        episodios: 16,
        elenco: ["Kim Soo-hyun", "Kim Ji-won"],
        plataforma: "Netflix",
        nota: 4.6,
        imagem: "https://i.pinimg.com/736x/28/1d/39/281d39121859e9f178a63f9c1b3e9a61.jpg"
    },
    {
        titulo: "O Amor Mora ao Lado",
        descricao: "O Amor Mora ao Lado é uma série leve e romântica que acompanha a vida de vizinhos que descobrem o amor nas situações mais inesperadas.",
        link: "https://www.netflix.com/br/title/81739044",
        tags: "romance vizinhos amor",
        ano: 2024,
        episodios: 16,
        elenco: ["Jung Hae-in", "Jung So-min", "Kim Ji-eun"],
        plataforma: "Netflix",
        nota: 4.4,
        imagem: "https://i.pinimg.com/736x/a3/99/ea/a399ead7d7e04d98e7878906591d6d77.jpg"
    },
    {
        titulo: "Beleza Verdadeira",
        descricao: "Beleza Verdadeira é uma série que trata da pressão estética e da busca pela autoestima em meio aos padrões de beleza da sociedade.",
        link: "https://pt.wikipedia.org/wiki/Beleza_Verdadeira",
        tags: "beleza autoestima drama",
        ano: 2020,
        episodios: 16,
        elenco: ["Moon Ga-young", "Cha Eun-woo", "Hwang In-yeop"],
        plataforma: "Netflix",
        nota: 4.2,
        imagem: "https://i.pinimg.com/564x/c9/b7/d8/c9b7d8c25c5590f9b956f455ad67cf50.jpg"
    },
    {
        titulo: "Hometown Cha Cha Cha",
        descricao: "Hometown Cha Cha Cha é uma série coreana que mistura romance e comédia, explorando a vida em uma pequena cidade costeira e os laços entre seus moradores.",
        link: "https://www.netflix.com/br/title/81473182",
        tags: "romance comédia cidade",
        ano: 2021,
        episodios: 16,
        elenco: ["Shin Min-a", "Kim Seon-ho"],
        plataforma: "Netflix",
        nota: 4.8,
        imagem: "https://i.pinimg.com/564x/cf/49/c2/cf49c28ac5c38d9b71deec2446a3ec41.jpg"
    },
    {
        titulo: "Sorriso Real",
        descricao: "Sorriso Real é um dorama sul-coreano onde a trama segue um herdeiro charmoso de um conglomerado de hotéis que entra em conflito com uma funcionária devido ao seu sorriso, que ele não suporta. No meio dessa disputa pela herança e desentendimentos, surge um romance inesperado.",
        link: "https://pt.wikipedia.org/wiki/Sorriso_Real",
        tags: "romance comédia drama realeza",
        ano: 2023,
        episodios: 12,
        elenco: ["Lee Jun-ho", "Im Yoon-ah"],
        plataforma: "Netflix",
        nota: 4.4,
        imagem: "https://i.pinimg.com/736x/42/75/89/42758958f8a21e23b3b2dba5f1e0e566.jpg"
    },
    {
        titulo: "Descendentes do Sol",
        descricao: "Descendentes do Sol é um dorama sul-coreano que conta a história de um médico e um soldado que se apaixonam durante uma missão de paz em um país em conflito.",
        link: "https://pt.wikipedia.org/wiki/Descendentes_do_Sol",
        tags: "romance ação drama militar",
        ano: 2016,
        episodios: 16,
        elenco: ["Song Joong-ki", "Song Hye-kyo", "Jin Goo"],
        plataforma: "Viki",
        nota: 9.5,
        imagem: "https://i.pinimg.com/564x/52/22/ac/5222ac64c58920d00a6b0cb805f6429e.jpg"
    },
    {
        titulo: "Uma Dose Diária de Sol",
        descricao: "Uma Dose Diária de Sol é um dorama que segue a vida de uma mulher otimista que, após enfrentar desafios pessoais, decide espalhar alegria e positividade ao seu redor.",
        link: "https://www.netflix.com/br/title/81572595",
        tags: "romance comédia drama",
        ano: 2023,
        episodios: 12,
        elenco: ["Kim So-eun", "Lee Joon-gi", "Han Ji-min"],
        plataforma: "Netflix",
        nota: 8.5,
        imagem: "https://i.pinimg.com/736x/33/2f/e4/332fe44ffcacfe9e131031f21ed6402b.jpg"
    },
    {
        titulo: "As Três Irmãs",
        descricao: "Três Irmãs é um dorama que narra a vida de três irmãs que enfrentam diferentes desafios enquanto se apoiam mutuamente em suas jornadas pessoais.",
        link: "https://www.netflix.com/br/title/81610895",
        tags: "família drama",
        ano: 2022,
        episodios: 12,
        elenco: ["Kim Hae-sook", "Lee Yoon-ji", "Choi Jeong-won"],
        plataforma: "Netflix",
        nota: 9.0,
        imagem: "https://i.pinimg.com/736x/cc/c9/eb/ccc9eb53fed831cbc4fce6293c4441f3.jpg"
    }
];